### ISSUE TITLE
Windows 10 Error

### ISSUE THREAD

**Issue by Oberown** [bbeardsley/BuzzIO#3]
Hello,

I have problem with the buzzers on Windows 10.

I have this message error
![error qr](https://cloud.githubusercontent.com/assets/8706381/10454567/bba97d78-71b5-11e5-8d22-68bf45ab554b.png)

**Comment by bbeardsley** [comment]
I just upgraded to Windows 10 and it works fine for me.  Are you building in 32bit or 64bit? I have only built it in 32bit.  I also initialize the controllers on the SourceInitialized event of the window.  Does this help?

**Comment by Oberown** [comment]
Hello

I built in 32bits.

I'm sorry, I use and old version of your code.
I'm updating this. But I have not the same problem. It's my users who use my application on windows 10 who have problems.

Exemple of code: it's write **0**
```
var handsets = new BuzzHandsetFinder().FindHandsets().ToList();

http://quizrama.com/Images/FAQ/BuzzType1.JPG
if (handsets != null)
     Console.WriteLine(handsets.Count);
```

A user with this buzzers haven't problem, black buttons.
![buzztype1](https://cloud.githubusercontent.com/assets/8706381/12832169/a879bbae-cb98-11e5-86d0-dffc47f52e4f.JPG)

The user who use another buzzers have the problem of no detecting. Collor buttons and the "hub" in blue
![buzztype2](https://cloud.githubusercontent.com/assets/8706381/12832224/f5a178ae-cb98-11e5-8f66-82c628ad2f9f.JPG)

Windows 10 detect his buzzer,  he test with the program quizXpress, and the buzzers works.
The buzzer have VID_054C PID_1000

I can't send to them program to test.
(sorry for my english)

Thanks for your help

**Comment by polychromenz** [comment]
Id like to use this but when i try with Windows 10 i cant get it to work. I dont have a PC here with older version of windows and as i havent run this code before i have no idea where the issue is. If anyone can help - even for a fee please contact me

**Comment by bbeardsley** [comment]
Like I've said above it's working fine for me on Windows 10.  If you can be more specific about what doesn't work I'd be happy to take a look.

**Comment by Oberown** [comment]
Hello,

I Have this error:
Msg:Failed to create device file WinEr:00000020
in  FindDevices

**Comment by Oberown** [comment]
Hello,

I have this exception:
When Msg:Failed to create device file WinEr:00000020
oNewDevice.Initialise(strDevicePath);
strDevicePath = \\?\hid#vid_054c&pid_1000#6&21d32633&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
in  FindDevices

I compile in x86

**Comment by javaprog** [comment]
Hi, I get the same error on one Windows 11 Pro machine but not on the other. The reason seems to be that I'm unable to switch the USB HID driver on the problematic machine from "HID-compliant game controller" to "HID-compliant device" as advised on https://softwarerecs.stackexchange.com/a/28309 - whenever I do this in the Device Manager, the driver switch is reported as successful but it doesn't change. Switching the driver works fine on the second machine, where I don't get the error. I assume that the CreateFile() call fails on the first machine, because the underlying driver (the one for game controllers) behaves differently than the one for generic HID devices.
